### ISSUE TITLE
dispaly pod name in Web app SinglePage

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [pokusio/kaleidoscopic#6]
* use `process.env.XXXX`
* andthis Kubernetes official trick (so easy !!:D )

```Yaml
apiVersion: v1
kind: Pod
metadata:
  name: dapi-envars-fieldref
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "sh", "-c"]
      args:
      - while true; do
          echo -en '\n';
          printenv MY_NODE_NAME MY_POD_NAME MY_POD_NAMESPACE;
          printenv MY_POD_IP MY_POD_SERVICE_ACCOUNT;
          sleep 10;
        done;
      env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
  restartPolicy: Never
```
* found it here : https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
* NowI need to do the same, but within a ReplicaSet :then i will scale up `Kaleidoscopic` 
* and then we can see visually all pods being updated with a new color, by the sidecar in pod
* last thing : 
  * create a simple CRD to specifiy a new Color
  * create the sidecar which detects the CRD from KUBE API (events) : 
     * I found one technique, using Prometheus (he knows how to detect CRD events),and aprometheus client in the app : https://www.liatrio.com/blog/kubernetes-custom-resource-definitions
    * rancher conf on this subject : https://www.youtube.com/watch?v=7wdUa4Ulwxg
    * What I need to implement aa Kubernetes CRD controller eg.in Rust lang.: https://dzone.com/articles/writing-a-kubernetes-crd-controller-in-rust
    * http://technosophos.com/2019/08/07/writing-a-kubernetes-controller-in-rust.html
    * A Kubernetes Informer in typescript : https://github.com/kubernetes-client/javascript/tree/master/examples/typescript/informer
    * A Kubernetes Watcher in typescript : https://github.com/kubernetes-client/javascript/tree/master/examples/typescript/watch
